### ISSUE TITLE
Incorrect response with using similar queries.

### ISSUE THREAD

**Issue by krychasto** [axelotecom/issues#4]
![issue2](https://user-images.githubusercontent.com/61030510/227879426-7bbf96bf-7c65-494e-a408-c6b633ff9eca.png)
![issue3](https://user-images.githubusercontent.com/61030510/227879437-db0236d0-aeb7-4d01-8329-74b55fce445c.png)

In the example above, Axelote instead of finding "select first_name, age from person where age > 40 group by first_name, age order by first_name" found "select id, last_name from person where city = 'Warszawa' order by id".

**Comment by krychasto** [comment]
![issue2](https://user-images.githubusercontent.com/61030510/227878669-3d47dbfd-5b81-4c51-93f1-e8efc11a956e.png)
![issue3](https://user-images.githubusercontent.com/61030510/227878676-47fe92f6-9944-4e63-aa68-7f3d801a47b2.png)

**Comment by GrabowskiKamil112** [comment]
![image](https://user-images.githubusercontent.com/84017437/227879269-af62b397-72f5-4797-a34c-2c1ccca88f1b.png)

in example above axelote takes only first sent version of query and returns correct data, but when the query param changes type: "total" => "pending", returning data looks still as it was first query

**Comment by axelotecom** [comment]
Please include code fragment

**Comment by krychasto** [comment]
![image](https://user-images.githubusercontent.com/61030510/228173271-37f08d17-cd45-4525-9802-6ccdacb2f43a.png)
![image](https://user-images.githubusercontent.com/61030510/228173480-92499522-57ce-475b-bf7b-53e32782cda3.png)

**Comment by krychasto** [comment]
const selectGroupBy = async (axelote) => {
        let query = AxeloteQueryBuilder.query("@sql select first_name, age from person")
            .append("@sql where age > 40")
            .append("@sql group by first_name, age")
            .append("@sql order by first_name")
            .build();

        let result = await axelote.returning(query);
    }

**Comment by krychasto** [comment]
![Zrzut ekranu 2023-03-29 184739](https://user-images.githubusercontent.com/61030510/228610564-ea6d4399-5623-4328-9731-3583ed30c0dd.png)
![Zrzut ekranu 2023-03-29 184803](https://user-images.githubusercontent.com/61030510/228610567-fa890902-0ce7-4df2-b0b8-60b192690915.png)
Now i have this error

**Comment by axelotecom** [comment]
Solved
